---
abstract: 'use IRC with C<IO::Async>'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  IO::Async::OS: 0
  IO::Async::Test: 0.14
  Test::Fatal: 0
  Test::More: 0.88
dynamic_config: 1
generated_by: 'Module::Build version 0.4001, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Async-IRC
provides:
  Net::Async::IRC:
    file: lib/Net/Async/IRC.pm
    version: 0.07
  Net::Async::IRC::Message:
    file: lib/Net/Async/IRC/Message.pm
    version: 0
  Net::Async::IRC::Protocol:
    file: lib/Net/Async/IRC/Protocol.pm
    version: 0.07
  Protocol::IRC:
    file: lib/Protocol/IRC.pm
    version: 0.02
  Protocol::IRC::Client:
    file: lib/Protocol/IRC/Client.pm
    version: 0.02
  Protocol::IRC::Message:
    file: lib/Protocol/IRC/Message.pm
    version: 0.02
requires:
  IO::Async::Loop: 0.54
  IO::Async::Protocol::LineStream: 0.34
  Time::HiRes: 0
  perl: 5.010
resources:
  license: http://dev.perl.org/licenses/
version: 0.07
