---
abstract: 'Asynchronous IRC client'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  IO::Async: 0.21
  IO::Async::Test: 0.14
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Async-IRC
provides:
  Net::Async::IRC:
    file: lib/Net/Async/IRC.pm
    version: 0.02
  Net::Async::IRC::Message:
    file: lib/Net/Async/IRC/Message.pm
    version: 0.02
requires:
  IO::Async::Protocol::Stream: 0
  Time::HiRes: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
